spring.application.name=pitchbridge

# 1. Conexão com o Banco (Ajuste o nome do banco após o localhost:5432/)
spring.datasource.url=jdbc:postgresql://localhost:5432/pitchbridge_db
spring.datasource.username=seu_usuario_aqui
spring.datasource.password=sua_senha_aqui
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Estratégia do Hibernate (A mágica da criação automática)
# 'update' cria as tabelas se não existirem e altera se você mudar a classe Java
spring.jpa.hibernate.ddl-auto=update

# 3. Mostrar o SQL no console (Bom demais pra debugar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Dialeto do Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect